backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /src/images

display_url: https://www.odemmissions.com/
logo_url: https://www.odemmissions.com/static/738ecb31adbe4110d4c7a5731ab74f5c/24f49/open_doors_logo_5.png

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Events"
        name: "events"
        file: "src/pages/events/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "events" }
          - { label: "Title of Event box.", name: "title", widget: "string", default: "Events" }
          - { label: "Body", name: "body", widget: "markdown", hint: "Use format: MMM DD | city, ST" }
          