backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /src/images

display_url: https://www.odemmissions.com/
logo_url: https://www.odemmissions.com/static/738ecb31adbe4110d4c7a5731ab74f5c/24f49/open_doors_logo_5.png

collections:
  - label: "Update Website Content"
    name: "content"
    description: "Add or remove upcoming events"
    files:
      - label: "Upcoming Events"
        name: "events"
        description: "Click here to edit events"
        file: "src/pages/events/index.md"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "events" }
          - { label: "Events Title", name: "title", widget: "string" }
          - { label: "List of Events", name: "body", widget: "text", hint: "Use format: MMM DD | City, ST" }
          